version: '2'
services:
  data-only:
    image: busybox
    volumes:
      - ./lampvolume:/var/lib/mysql
  lamp-server:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    volumes_from:
      - data-only
    tty: true
volumes:
  data-only:
