version: '2'
services:
  zabbix-server:
    build:
      context: .
      dockerfile: Dockerfile-zabbix
    ports:
      - "80:80"
      - "3306:3306"
      - "10051:10051"
      - "10050:10050"
    tty: true  
